print('Welcome to the Band Name Generator')
city_name = input("What's name of the city you grew up in? ")
print(city_name)
pets_name = input("What's your pet's name? ")
print(pets_name)
print("Your band name could be " + city_name + ' ' + pets_name )